# basic Workflow with 3 Envs

name: Workflow with Three Envs

on:
  workflow_dispatch:

    
jobs:

  Dev:
    runs-on: macos-latest
    environment: DEV
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "Running Job in Dev Environment"
          

  Qa:
    runs-on: macos-latest
    environment: QA
    needs: Dev 
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "Running Job in QA Environment"
          
  
  NonProd:
    runs-on: macos-latest
    environment: NONPROD
    needs: Qa
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "Running Job in NonProd Environment"
